apiVersion: v1
kind: Secret
metadata:
    name: ezbookkeeping-secret
    namespace: ezbookkeeping
type: Opaque
stringData:
    EBK_SECURITY_SECRET_KEY: ENC[AES256_GCM,data:7xYnS2d/AGvrjY1N9qN3/16ZnUdsd1FK5afHxtzQevxG7sI15m2cvKfy++g=,iv:f6Q3F10t1wTizAcnDQ5uT6aMoiGD1638km1YBz6Sasg=,tag:sqzufWyB+Y3jqMTyux5vjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib1VVRmkzSXorMVJXbERn
            RmJxTWU5YkZ6ZnU4cDlsVHJqMHU4ajgxa2xJCjB5SmhFR2ltcDdKY3VsQVBoYy9N
            NSs2Q1o2c2J5UWIrWE9ZVy82OG5ERkEKLS0tIHU2aE55bzRNS2ZDaDJGeDVsdlBU
            dUpzSHpPQ2M4T1U1VEhzcGo0T2MvcG8KDA0U9c+ZhE7Kj7sXbcaRk/7QYs1ias9x
            t0uth6xn+5kH9183ZQG/CKop8q5BT6AFocpRPO1ZnnFKzrszvSfMAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T17:22:01Z"
    mac: ENC[AES256_GCM,data:+d9+IyIB9x+79MXwE0Dzonxkj6TMS6zEarlyMvx4S8s1ltydiwFUr00fmLcWBy9rJExsIoBGZrBNzrx6Oioxk/VcllmNnLjmYSYXuqK9e98xBcrfqnpIOjgcdHlFNQHSviRAoyE250sVnGvnDgypqt5Gnif9tmC57GYwq5osu5g=,iv:I6SMXsxcns5QBbjB2NUhVoFV/l2c7r767ikKL56QWYQ=,tag:F4jcXTE5lxLdKMKYAUTRkA==,type:str]
    version: 3.13.3
