apiVersion: v1
kind: Secret
metadata:
    name: ezbookkeeping-secret
type: Opaque
data:
    #ENC[AES256_GCM,data:U3CXNLDfOBcgZq8n2M9dOzOwuSHXcC9Pexsy8nyXS1xBBMaWG7ROpuryuydt593R8zEwA1hdvUl6Q2QH2S/iiksUld8m4qdxY8s1ktlnopR/GI097hPY2pS/8KA4bKdJk9gA239RTvHq0kBb7GlwI+64+t1uCeU7TRsTBbDDqE7DlXxhU454Z/LRQMx7FWZp3LtCdsewhyf8NQw=,iv:8T4+jT9dPXxRJ02RMDQ9jXvT/7KJs1aoXX5zzbsh54o=,tag:e3sT3pqcnIYFsX3Z9lzKUg==,type:comment]
    EBK_SECURITY_SECRET_KEY: ENC[AES256_GCM,data:QZmz3i/kMdACzI2qHx/IxZF1drAdqux++3dtjBV0DvxK+b9E4dXNe2K85Zs=,iv:xl2SxglKfNC8+HnxUvtgApzYq7fD1i4n5mIF1PpuR1A=,tag:VgNLSWzzXUV+Z11e/bbUgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcE1GNDEzR3FCWll5Q290
            LzZieENMYkVTYmMrVUtzZ3Z2dXIyaW9TVXlvCmlWbnNiMThkL3REYnR4cnUyVWhY
            R2ttVnhpa09UWXFzRnpuYytGSitkMjgKLS0tIFA5ZVZ1UmVPTTV1OWs2VnE5TnNW
            ZC8yUktpSlJHV1ZobVczQjh6UTBKME0KZqenD+eI+rOL539ftDdyC254TcTMeh4Q
            v8aUS42y7jL9u4Ur/X1CqNBBp5TuEnw8xBpaa9nStkqvhrEttMoT1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T11:50:01Z"
    mac: ENC[AES256_GCM,data:3OIox/OMQh3lHkLFzDo8/SrLEuzlwANFSuGSWCS9UBhmav+WpCLf9vpvw90Xf53KEcQaOr3PFoojfCFsFMpVjrMQ7/w5/9cRr90nel+g7rwkD1fOJEhs1plMUcgK7EdMlLrjj/Bv7PQfTCDGRY1lsOPzZw4fBZ/rqJ0s5NFdgG0=,iv:FGMhZbX9ncEEI/+aO2KsWzcOpq+jMxZc987awO0yq4Y=,tag:ryui4JUJXGKyLprTVGWptg==,type:str]
    version: 3.13.3
