apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./cnpg
  - ./kube-prometheus-stack
  - ./longhorn
  #- ./metallb
  - ./reflector
  - ./renovate
  - ./reloader
  - ./spegel
  - ./traefik
  