apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 2
  bootstrap:
    initdb:
      database: app
      owner: authentik #Set to db username
      secret:
        name: authentik-db-creds #secret containing username/password in basic auth
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-global
    major: 18 #pin to major version required by app
  storage:
    storageClass: longhorn-cnpg
    size: 10Gi
  #plugins:
  #  - name: barman-cloud.cloudnative-pg.io
  #    isWALArchiver: true
  #    parameters:
  #      barmanObjectName:

 
