apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: opaque
stringData:
    AUTHENTIK_POSTGRESQL_NAME: ENC[AES256_GCM,data:8G3o,iv:ZGmWLNN30/UYoROaKgbis8rAxnLysWE+lz3nbmGXiLQ=,tag:pj5fhV4c8AWPj6HtJOKB7Q==,type:str]
    AUTHENTIK_POSTGRESQL_PORT: ENC[AES256_GCM,data:lFcWeg==,iv:uwZwjcMl19df7nnfsl9T5RaO84ZtY3cFCycY5ymFHgY=,tag:ph7FJALeB9n8iUVotViGbg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:rbv7AhSbGdBcoQvqDCtrLS1ejKyhJ9pm6cFNUD+8vqbi7jjVZV8XskfaTR1MTqiUV/mqJSLD3Smrft2b9mzAy3XsrfxwZpmxVWsqi1/0+Cfo,iv:XicP8IMu1QtzGnV2fVWnIm/UEuIcdS7nTQX5Y6quhD0=,tag:slor36pMMFefeMWEA3IMBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzckNSbFRzM0tuK1I4eFh0
            Q2w2elNyK2M5Q2hRSHdJRUlWbEsxa0g0eUd3CkR2TktoeVRpTWNUVFcwVVJRdjgy
            QVRhZ29rRkYxc25Kb0FCYkwyTjFGaGsKLS0tIFh6aVFVQkFWWlprMVdBUFM2WXk2
            L0xDVE1JMUdMOHhibmZUVno1OFFqWWcKPUpPikWE3O4nD5BfZc/pcewtp1J2Cd3w
            yhg8TVu+BL2DwS2h94C793n4zz36yFJPSH3VjtPYU88VmzsTmoFuvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T00:33:02Z"
    mac: ENC[AES256_GCM,data:fSTuH9Jji57eoNfjnylkxNUkwpaSQpicub2T1sL60zMhwBKJJ9ZuF2BDNC4urkN8M2vDnxM9KjTiPGgHG7IWvnVBTSzI2EwcypdGrbxoiwbg/dutJU/MqoNw4ZaX5eZz7u933O8C1Z3wD9qUog3alspKggtM3DBpg5eQ/Rh5yFs=,iv:v9D3tiWwvZ5mNk3yxF4+vXFh0zNiA2dbGcPQQvmOCqk=,tag:u3RvldeCpZ3IkzDeSH9xKw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: authentik-db-creds
    namespace: authentik
stringData:
    username: ENC[AES256_GCM,data:1P2S3a0pnetA,iv:0ZJtwy0KU/RIJggcf2/fFoU/lc+Y4VqcUdKDWOrAxg4=,tag:vGDoTu0j3zahOerEoEshCA==,type:str]
    password: ENC[AES256_GCM,data:9JaXFLNGZFntlk3z9G0PWj1ncNBrWXEp,iv:MJ5lAPXinCFJtF2IERtcSKst9996RCdzIeqIyfYbhGk=,tag:w4ayPkW2sFPWSz/ecBkI6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzckNSbFRzM0tuK1I4eFh0
            Q2w2elNyK2M5Q2hRSHdJRUlWbEsxa0g0eUd3CkR2TktoeVRpTWNUVFcwVVJRdjgy
            QVRhZ29rRkYxc25Kb0FCYkwyTjFGaGsKLS0tIFh6aVFVQkFWWlprMVdBUFM2WXk2
            L0xDVE1JMUdMOHhibmZUVno1OFFqWWcKPUpPikWE3O4nD5BfZc/pcewtp1J2Cd3w
            yhg8TVu+BL2DwS2h94C793n4zz36yFJPSH3VjtPYU88VmzsTmoFuvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T00:33:02Z"
    mac: ENC[AES256_GCM,data:fSTuH9Jji57eoNfjnylkxNUkwpaSQpicub2T1sL60zMhwBKJJ9ZuF2BDNC4urkN8M2vDnxM9KjTiPGgHG7IWvnVBTSzI2EwcypdGrbxoiwbg/dutJU/MqoNw4ZaX5eZz7u933O8C1Z3wD9qUog3alspKggtM3DBpg5eQ/Rh5yFs=,iv:v9D3tiWwvZ5mNk3yxF4+vXFh0zNiA2dbGcPQQvmOCqk=,tag:u3RvldeCpZ3IkzDeSH9xKw==,type:str]
    version: 3.13.3
