apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: miniflux-db-creds
    namespace: miniflux
stringData:
    username: ENC[AES256_GCM,data:aSMdgZsXreE=,iv:EAlaoDB0oMs48TqxgkuPp6Hlq+g0rcO6zQLxPWGfDk8=,tag:5EznH6fsRLPY4OfmkISCmg==,type:str]
    password: ENC[AES256_GCM,data:wvzFalvYfOak5bcF1BKASQ==,iv:Emlv2+cNSCo2StpzMETINjqIGS3AX0LBFHaxC8TS2ho=,tag:l5XXNla/W02Asofd0Be3ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWlJuV1ZLQVdmNzdHT0Zh
            QWVZTUtXQURQZGxWNHBQdkViSHV3ZGNuQW1JCmxkOGhhSExaL1hmKytFZ3JWWWc4
            U053SlE5ZVhKcjIvcHhDSkR4bUY3bGMKLS0tIEZNRU5mOGVDbnE3L0JOZEZlRXVj
            RUVBa3pRK3FEYm5heHg3amxBVWdSbWcKLT46lUPw22EARG1vHvhUqD6B6l6D9PFB
            i+ibIpZtZ+r0/wSqibCt7dHP/u1dh3k/dIYpQA1NsKYuu6nBz7+flw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T19:59:52Z"
    mac: ENC[AES256_GCM,data:o0N5M/FAmzTZnrfFt4DYGgrrEphV1A61D9z3YlWHs9Hpj152+hZE3vBHGTeHXrDkcWTYLowfiLqYrMpZBUFn8Nd8qMmXljKJbeh4Zw5ZeOjOIZMCAqBZ77nJdcOqRSS6diLN1IUo7wJH0snxtB+2V7gCiZcTfGUT0eCtsLROAMQ=,iv:UxR9FLlLkFL3EgI5Vd4I4EmsCl7NMWubAKDtS/G2b2o=,tag:IiOjEhblEOJDfGmOMmwnlg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-admin-creds
    namespace: miniflux
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:IY7H0rk=,iv:5xWxbKcsvBOQ4a3O7Dn36lcAoWbvjthBsT9EGThuY+w=,tag:eIz+tlbPCqLWi2HTLhh2+A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:87UpD2VSjiA5VMiFQGAd6Q==,iv:vLim3CXGQQVQTJ8RpiamKqg5RGF+rPjphvBRy8NJssM=,tag:s/MofBeXDlFz5CyLFP48HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWlJuV1ZLQVdmNzdHT0Zh
            QWVZTUtXQURQZGxWNHBQdkViSHV3ZGNuQW1JCmxkOGhhSExaL1hmKytFZ3JWWWc4
            U053SlE5ZVhKcjIvcHhDSkR4bUY3bGMKLS0tIEZNRU5mOGVDbnE3L0JOZEZlRXVj
            RUVBa3pRK3FEYm5heHg3amxBVWdSbWcKLT46lUPw22EARG1vHvhUqD6B6l6D9PFB
            i+ibIpZtZ+r0/wSqibCt7dHP/u1dh3k/dIYpQA1NsKYuu6nBz7+flw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T19:59:52Z"
    mac: ENC[AES256_GCM,data:o0N5M/FAmzTZnrfFt4DYGgrrEphV1A61D9z3YlWHs9Hpj152+hZE3vBHGTeHXrDkcWTYLowfiLqYrMpZBUFn8Nd8qMmXljKJbeh4Zw5ZeOjOIZMCAqBZ77nJdcOqRSS6diLN1IUo7wJH0snxtB+2V7gCiZcTfGUT0eCtsLROAMQ=,iv:UxR9FLlLkFL3EgI5Vd4I4EmsCl7NMWubAKDtS/G2b2o=,tag:IiOjEhblEOJDfGmOMmwnlg==,type:str]
    version: 3.13.3
