apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./audiobookshelf
  - ./calibre
  - ./ezbookkeeping
  - ./excalidraw
  - ./kasm-workspaces
  - ./karakeep
  - ./mealie
  - ./linkding
  - ./paperless-ngx
  - ./miniflux