apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./audiobookshelf
  - ./calibre
  - ./commafeed
  - ./ezbookkeeping
  - ./excalidraw
  - ./karakeep
  - ./mealie
  - ./linkding
#  - ./n8n