apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fossflow-config-pvc
  namespace: fossflow
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi