apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: commafeed-secret
    namespace: commafeed
stringData:
    username: ENC[AES256_GCM,data:9JR0yo8ZWBMN,iv:Q/9zDr4lMxJXmkAeXIFJIVIvgB374OhjqSNN9wcQM8E=,tag:s5tHaHh9qJ72WLpB6zCWqA==,type:str]
    password: ENC[AES256_GCM,data:/j48Pf7X4IvmHoD9xmmr/L4/81/v5+Y3,iv:rvIWIklqWef+w60LNAVGfqQYlWKsJFVKJn+XrcJg/6E=,tag:piuYVKTKQkYcrvQGHASn+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia1dUK2VZQVVjb0NONHk0
            QjE3ODdBRytjMWtrNndjVndHQ3QrTjQzOVFRCnBPNDVvMG04TTRJeWpkYWlpeGlL
            eEFBK3ZMdkk4QUxqemdaTU9zaDlTSXMKLS0tIEdNbXRZMkF4RjErcUVid01FZGRB
            bWxrZDBSUC94WWxVM1laNkJSSCt4NFUKO3JInuVg/AbyHyc4fRPNwqS74jY3EHIN
            drTPEJnxPhkLj6L11FdWHQyFC48MdMdgWhEmcwCWqIa0XImk7AZ5kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T00:37:46Z"
    mac: ENC[AES256_GCM,data:faLET2Daut0bPwf9nle5BsPaqhNyMT1URnDY2ntJ4y1gccZrqA1DK55OBE4VHx8MzcQSbS9Ii/lx07i5732Vs8lwD6kazh8U6DsydEOjUyDCq7FGmxbyj6u5UoZi4XebOEdpQUzCxZISDjTeUElky0ujzY4a5s5Q0Y/m+QycVII=,iv:aK7IKdw9VyukF+Y4PxsmVByDg9Y5Sy3/zjgg5ZhNND0=,tag:rbrpgAHOWbj7/Ri0G90U5Q==,type:str]
    version: 3.13.3
