apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: calibre
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: crocodilestick/calibre-web-automated:latest
        name: calibre
        ports: 
          - containerPort: 8083
        envFrom:
          - configMapRef:
              name: calibre-configmap
        volumeMounts:
          - mountPath: /config
            name: calibre-config
          - mountPath: /cwa-book-ingest
            name: calibre-ingest
          - mountPath: /calibre-library
            name: calibre-library
        resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              #cpu: 1000m
              memory: 1Gi
      volumes:
        - name: calibre-config
          persistentVolumeClaim: # PVC Claim in storage.yaml
            claimName: calibre-config-pvc
        - name: calibre-ingest
          persistentVolumeClaim: # PVC Claim in storage.yaml
            claimName: calibre-ingest-pvc
        - name: calibre-library
          persistentVolumeClaim: # PVC Claim in storage.yaml
            claimName: calibre-library-pvc