apiVersion: v1
data:
  banned-password-list.txt: |
    password
    12345678
    123
    OpenCloud
    OpenCloud-1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: opencloud
  name: opencloud-cm1
