apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v3.28.0
        name: mealie
        ports: 
          - containerPort: 9000
        envFrom:
          - configMapRef:
              name: mealie-configmap
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: mealie-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mealie-secrets
                key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            #cpu: "500m"
        securityContext:
            allowPrivilegeEscalation: false
        volumeMounts:
          - mountPath: /app/data
            name: mealie-data
      volumes:
        - name: mealie-data
          persistentVolumeClaim: # PVC Claim in storage.yaml
            claimName: mealie-data-pvc
