apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: mealie-secrets
    namespace: mealie
stringData:
    username: ENC[AES256_GCM,data:s4p3mc/o,iv:wLyzBMwUt/RU/xekoqTLu86fE8cEEH4FeYpUEMXqAFs=,tag:/ljpJxqL1JLFIk9BxCaVrA==,type:str]
    password: ENC[AES256_GCM,data:qmzbnLy6F10YzuBL5fDyrpOfhTIQNPu3,iv:HwpNAOZpFRiOoRudeCCOssGkPhsiAfRzKuuRDxEAlbk=,tag:tXUzEE7JWy29BSw3dXxU+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndzIxRm1iZHgxR204b1h0
            V0RmeXRoUWhTV0MxbEJKSWFSelo5UnRTY2dZCldCcmd5c3NFM1FqMzJwdUZONVZC
            VWNKdXN6aE1VS2xacEpUdkpUTmJWVTQKLS0tIDdBbVFVVlVVUjFkcU96MENBT3h5
            bnpYZnZKNUlOTFdJbktGSFlYR2JyU0kKW/0xuhd0Jr38hdiBwLP8pjqEuz9gFUYN
            jeOfrLQ507fZiFLxqEZ5xzz0T++zKgBfSMpwoKxnqMUCaolPZFiI6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T00:14:17Z"
    mac: ENC[AES256_GCM,data:8J8GeAbhIv4W9fgiGBF3nYyr+u/sM74PLdcUYaAyVJCYWxjCPxOrR3CMxlVWpOjw82Fp27R8wkHa+d81qyzmTf8k1JcVzLxIvp93YSijxkTlPDbNo6uxCUjWuT4Rf95YPm7dy3qbPs/8iOH/Sighi9lBNuaeypTSFRTD5HdZ0qA=,iv:YNvvT3c21eGDyWF1zIan3CPpkW7l8G84aCPzlmd/D5o=,tag:eXc8SKbLpNq5wfU+XmiPKA==,type:str]
    version: 3.13.3
