apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: mealie
type: opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rTjweIothOjcWxDpABfaZOtBGnBLUM+c,iv:UnssARYBsNCib9kcTCqHae/poSx41EfU13dJMr8l+as=,tag:3zBvqvSG9TUg+HhdO7kT5A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Nvddfhb9,iv:jVgJ5ZiLKpRvuhN4PJ985Y8cvR5JEHbnlO7+ih25Dds=,tag:m9gg6WsT5PRS+HzlGRC1+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdnhRQTFtQUlqVGZlWjU3
            OUtDakVZLzBOaHhXOEF6STZzcW5qQ1J4amxrCi96VG4wZXRUeklqdzI0SFpydklW
            TTU2cDJMZTN1L2FRTE9ONHZXd3cxNncKLS0tIEFlNHkvNnFESExTQSsrRWRBSC9J
            UHorOUxGUEdFdWJEOXlhVk9NekhrSDAKzdAup+xMY/ryId/AFROcWhLqkXvZpXz9
            QUxfv4YUSLII8CDqbr/KkP4QN2xZcoUdKwfZBJhj6eFQNNd/vu/R0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T00:54:46Z"
    mac: ENC[AES256_GCM,data:bSveYwqWVdMil3voyNPM63HngJ4tvY1sKZ2PscE8i2g5VVIfj/rgEO73DcMQaVOo40BuvbOzkC35D63dUw3eMces8krunu1vjPMKfBXwkz20KAOB0caSGzInbpwZLRXR/IdwadST+DLbhuxl3T5zKQpo/Yv5WwNRC4ANsHlFMPk=,iv:6pbYYwla2yQtoke1oANPE8hkCXwx2FNYiFDbvFD+KxU=,tag:ZWVlNuPtV2b+NMmU/pkGlA==,type:str]
    version: 3.13.3
