apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: mealie-secrets
    namespace: mealie
stringData:
    username: ENC[AES256_GCM,data:2W3YhpfE,iv:PnRhVa6WvbcY6N1U+J2jSzyKAF07VIeen17lMJ4TCKA=,tag:tWENLq/jGh8/TuiIcOfQ9w==,type:str]
    password: ENC[AES256_GCM,data:sllBlbXpfpNIQHajoh3uDcRaUODtzZtR,iv:n1C0z4IsrMP99f5/cfhtV56fqW13y3GrG50DP8g368U=,tag:TlQDVIClE5HDxbmPu0eBGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNUZWNkJKZU5SQkZTU3RP
            ZEIwYURRdGdBMmZBeEZMVkNCd1lhSXd6MGpnCitsRHNBeVF3NExEZU1OWGpGM1hh
            aWliaFlWV2RQdEZTNFgyOEVLTVlZVjgKLS0tIHVleUIrUm5KMm9KdytDQ0daMUxK
            SHdhdFBzc0lIVlhhbUJLMjJyNEtVYUkKWG71D9PNYv0+2iOaEHx38qcDG3ZZSV4T
            g7QwDU1bKglj+S69q1UuujuqNzYOd2jtGYQNpiKoJvvUqrV8nSfbyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T13:01:47Z"
    mac: ENC[AES256_GCM,data:Mq+b3CxcCVxPilzAvlRvYcy8HTBIhjKYqnweVoy+iCTUPj9ui/Y5AGE6EGyJT4lYxUVgq0B6vtb3uFpQMlWZtQ9OJmKFUs2K8GAS2rCYBPpSufveyKyCHm3k7cw00rrbEbOFrPqems/MqR3P96HavkGp4lV4w87wrhKLxSdz3Zk=,iv:GI0jUNQKS9ASvIvbYmQNWNfKmbgYHM00KfYNihS4P7k=,tag:xNbP4dDD5qTEJQ6dHoxFsw==,type:str]
    version: 3.13.3
