apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
  namespace: commafeed
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: athou/commafeed:latest-postgresql
        name: commafeed
        ports: 
          - containerPort: 8082
        envFrom:
          - configMapRef:
              name: commafeed-configmap
        env:
          - name: QUARKUS_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: commafeed-secret
                key: username
          - name: QUARKUS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: commafeed-secret
                key: password
        resources:
            limits:
              memory: 250Mi
        securityContext:
            allowPrivilegeEscalation: false
        #volumeMounts:
        #  - mountPath: /commafeed/data
        #    name: commafeed-data
      #volumes:
      #  - name: commafeed-data
      #    persistentVolumeClaim: # PVC Claim in storage.yaml
      #      claimName: commafeed-data-pvc
