apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: commafeed-secrets
    namespace: commafeed
stringData:
    username: ENC[AES256_GCM,data:pbCfHCB09XSE,iv:b36pf9RHZ1eGsYD29nWJFuQ6vw4C0E0GtAiE6TGNcUY=,tag:iT5HfPX8chokuDNwChFHVw==,type:str]
    password: ENC[AES256_GCM,data:rWI9MoJcpLPod2K+849UyuChA8SB4McN,iv:JpHx9uCMhzsevg7BWn552lTuEpHLld+cul86PRq/62Q=,tag:GddAawsQmo6d24gyfxmY1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTk9QQ3g2U1FmMHEyZi9I
            ODRMZ0l2WDhldUpIdFhEeUpGOHRXQzVCN3djCkVHMGJ5UTBrYWRTTEQ4RkxBc0dQ
            MzJ4NTBFaFQvQXJ4NTl4dFVaYlV0WjQKLS0tIDhYOFlQVzFUcms4aWhybUY3WG90
            NFFzRUFjRW45ZURlTXFjMWZJTC82YTgKC5EGQy+9hhFWaAuN1yR1vJzy+aqjs6mH
            AN/MNFt06f0oE+MdzLOAtgqY6wu7CyjIf5GxifPhi4RQID8rDUQ0Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T23:29:54Z"
    mac: ENC[AES256_GCM,data:uugPF7d4w2LnMHzEbJsARO/tO+uwRhlEWETDicEsXx859pA6iiQ74/QZiACf5actd61QWSW61/dkBvYY9KjVOZBS6d0g5oHnZ3KojwQUI/WDXmXi+4AdhIf5sISyoncCd0nLreW9kYLBVNEvhDjPHKozcNScuk6m6zNvtpYKU1Q=,iv:35dKqJmU3xIMDCByyRydnWbuOpXHh35cbCxUvp9LK3w=,tag:/jVbR1sYTbq06l5E27lfog==,type:str]
    version: 3.13.3
