apiVersion: v1
kind: Service
metadata:
  labels:
    app: commafeed
  name: commafeed
  namespace: commafeed
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: commafeed
  type: ClusterIP
