apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-configmap
data:
  NODE_ENV: production
  ENABLE_SERVER_STORAGE: "true"
  STORAGE_PATH: /data/diagrams
  ENABLE_GIT_BACKUP: "false"
  #HTTP_AUTH_USER: ""       
  #HTTP_AUTH_PASSWORD: ""