apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: karakeep
type: opaque
stringData:
    NEXTAUTH_SECRET: Vpx4Gnqms1giB7f6dMGcmonv3NoChHzQHnslJ6l4E1k+UD+N
    MEILI_MASTER_KEY: W6WV0S1BfL6sglp+motHZxMTKhsX9r6233YmOlcn5gxQtEpl
    NEXT_PUBLIC_SECRET: HTjSu9XWOqUR5P1mfCNzaNVqnhFa9Cvs4Ce84bVBVGawdmm0