apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: karakeep
type: opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:cu8nfg1ZBBUXauAoHRqRbLrY7Vb9FplG7ewT6y9iPd3UMa3lsZ7zgSTB5zOAXMUc,iv:eqMDvYrD6chJFDuv73PCjkwTrn02oLGFW/FlSRhdk2U=,tag:Yvx5X0ze00tk4KP7WrcixQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:K+1HpFnjRCOUbLAXerOjAxmByKZudOHcg//9neN7M/HlqEsOEWf6Gix8dHRgABMuYg==,iv:ISKXGMbYG0lTh4OoYf2pnbJMYgo7YF46rxBqH0N3Rds=,tag:rrSN2btNN9QlXdoSXU/1Tg==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:EF3DmCPAlBwhoEoV2ZXaQMUil5Wx+KfLTL/L4fdQB3aGTJ37bOnN644NOE2FWX0Q,iv:SXMfPhg1/4xrbjVjoY5gS2dVZzzyNPEi9iAGr4x0xis=,tag:SRJ13litbYKNfSHJMDULfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQVpyNXpTTkhXRXg4SXlh
            RUltNjBwTzZEL2ZqMERKa0ZUcWphZ2t6N2dRCmh3dUVYWVpMUmp6Rk9XNXE4bEpr
            UHFtOUpoRzRNMzJtV1lSSjBOYzFFT28KLS0tICtzeGFURVVmdG5lVkozQnQzcE9a
            TjdjTkZPMU90anJRaHZRek9PRGQwancKWOhq8uAvlYltcoq1Z58Ymg+ipNZBxdhj
            NlbI4pkutvLQi7+Ueegd3hCjTnFAc9nb95HAwr6DPXEek0rqhrwH2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T20:50:19Z"
    mac: ENC[AES256_GCM,data:9WA5jTYL93je6rJBFiZkvnnuKHwdVBHZKi3BZyvHBwwsikY2hGHEO5nW2yZUPtJ/O4wPAqJrvC5gdSOm5+RzBChWBzU3vV7avnU9vriv6Vgvez7li24delyxfbt17sseIdCjw1Ru3BRxvZQl08oEOoI/wT+v8Un5olN4hqwMkQ0=,iv:VuCw3A2fR80qNZhleQ0pXylvWtObs6cPUXHtRYYRsgs=,tag:mYj30/lHj9j+4g/4ucTUDg==,type:str]
    version: 3.13.1
