apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-configmap
  namespace: paperless-ngx
data:
  PAPERLESS_DBENGINE: "postgresql"
  PAPERLESS_DBHOST: "paperless-ngx-db-rw.paperless-ngx.svc.cluster.local"
  PAPERLESS_DBNAME: "app"
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_OCR_LANGUAGE: "eng" # The default language to use for OCR.
  PAPERLESS_TIME_ZONE: "Europe/London"
  PAPERLESS_URL: "https://pxng.ksefuke-labs.com"
  PAPERLESS_REDIS: "redis://redis.paperless-ngx.svc.cluster.local:6379"
  USERMAP_UID: "1000"
  USERMAP_GID: "1000"