apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-configmap
  namespace: paperless-ngx
data:
  USERMAP_UID=1000
  USERMAP_GID=1000
  PAPERLESS_URL=https://paperless.example.com
  # Generate with: python3 -c "import secrets; print(secrets.token_urlsafe(64))"
  PAPERLESS_SECRET_KEY=change-me
  PAPERLESS_TIME_ZONE=America/Los_Angeles
  PAPERLESS_OCR_LANGUAGE=eng # The default language to use for OCR.

