apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-ngx-db
  namespace: paperless-ngx
spec:
  instances: 3
  bootstrap:
    initdb:
      database: app
      owner: paperless-ngx #Set to db username
      secret:
        name: paperless-ngx-db-creds #secret containing username/password in basic auth fornat
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-global
    major: 18 #pin to major version required by app
  storage:
    storageClass: longhorn-cnpg
    size: 2Gi
  #plugins:
  #  - name: barman-cloud.cloudnative-pg.io
  #    isWALArchiver: true
  #    parameters:
  #      barmanObjectName: