apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: paperless-ngx-db-creds
    namespace: paperless-ngx
stringData:
    username: ENC[AES256_GCM,data:4CthwELS5a/MvQCWYw==,iv:kDQt7WO1QUp3b7DVbvtke+g4JgVOdJEUt7I9Uz8TStI=,tag:YIOuEEtTmyuVb7uGDMKFYg==,type:str]
    password: ENC[AES256_GCM,data:d/Wjb5dnDo5tzqH3PfYkETzBIumTFLdg,iv:yU6wvkQkPwFOdREHD1VseXSwgvdvNPMozDGUJGwE17Q=,tag:7o3gdh41Iyx9VOa8YHwwFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWjluYTNrUWswUzRsVVBh
            T09pcE5FK0FKR050ajVpM2Y4ZG9qci9zWVJBCjc2YWJCekRJdGw1bnE2Ykszc1Va
            RFNtZUhZeXF6b2ZJRmszdk5VU2M5aFUKLS0tIEMwMUNNYlA5ck5USmhabHdwN1Vs
            RFZBdHNRSlloY2lOSk5FOE41TzFSaGMKRY31kWHSWDPSwF/zjpvN0iSjqm/r7EJP
            Be/V/UtOL+Nn3ewj2EnZzGwBnovzQ4dlbKIDwv8SKVzWkc8xdraJXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T00:55:02Z"
    mac: ENC[AES256_GCM,data:i51KrNmkyQ3DElKj5dFT7c082OfxbD9PicqziO2Jg8Z3+S83EVRj8t893lzcyJXxVDobDzb3mNcyyekAoFaC46DBJZjw2UFeSA0fCM4sTJHSr6bMn49CObRKioaq9pBGFY+Dn8+d1C7WNZJPI0+fPJDN60Pss62XR4Ne3mgHpzY=,iv:sZkzE5irWV9lgik8/E/YYSIzFzW6yYC27gPLLYaraSI=,tag:XLWdlLRuV919pPSrwJiY+g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
type: opaque
metadata:
    name: paperless-ngx-secret
    namespace: paperless-ngx
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:4JJV0u2DMwq71N/hyxJwkavme3vVgaobi2lnsKQBRctntA/v8XCbMm4B8UOQJdchksMjVw9OAJ8lzfihfQl/axqHmwxc6f+EHs6IE9YavlV9uczDEcE=,iv:mEogslrz7w3XVfrioLcbwxeAqqqsnRY0CxsIqU8daoo=,tag:L48W3nDJlPAEgkZnT+Gn+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWjluYTNrUWswUzRsVVBh
            T09pcE5FK0FKR050ajVpM2Y4ZG9qci9zWVJBCjc2YWJCekRJdGw1bnE2Ykszc1Va
            RFNtZUhZeXF6b2ZJRmszdk5VU2M5aFUKLS0tIEMwMUNNYlA5ck5USmhabHdwN1Vs
            RFZBdHNRSlloY2lOSk5FOE41TzFSaGMKRY31kWHSWDPSwF/zjpvN0iSjqm/r7EJP
            Be/V/UtOL+Nn3ewj2EnZzGwBnovzQ4dlbKIDwv8SKVzWkc8xdraJXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T00:55:02Z"
    mac: ENC[AES256_GCM,data:i51KrNmkyQ3DElKj5dFT7c082OfxbD9PicqziO2Jg8Z3+S83EVRj8t893lzcyJXxVDobDzb3mNcyyekAoFaC46DBJZjw2UFeSA0fCM4sTJHSr6bMn49CObRKioaq9pBGFY+Dn8+d1C7WNZJPI0+fPJDN60Pss62XR4Ne3mgHpzY=,iv:sZkzE5irWV9lgik8/E/YYSIzFzW6yYC27gPLLYaraSI=,tag:XLWdlLRuV919pPSrwJiY+g==,type:str]
    version: 3.13.3
