apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: paperless-ngx-db-creds
    namespace: paperless-ngx
stringData:
    username: paperless-ngx
    password: fVgM3mjJ0s0sCKQvXSBVSuwX
---
apiVersion: v1
kind: Secret
type: opaque
metadata:
    name: paperless-ngx-secret
    namespace: paperless-ngx
stringData:
    PAPERLESS_SECRET_KEY: 3a1vmk6SOPF0kUUzhETP_mGHhRwKuFp4LuM3w8qIfXSPaJomtJVLfkEor2G_hIMvvEEpJzUNf70wFILEaqkZ_A
