apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/networking/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metallb
      namespace: metallb-system
# Fixes ip-address-pool.yaml and l2-advertisement.yaml CRDs applying before Helm Chart is deployed