apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 30m
  chart:
    spec:
      chart: goldilocks
      version: "11.1.0"
      sourceRef:
        kind: HelmRepository
        name: goldilocks
        namespace: goldilocks
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    vpa:
      # vpa.enabled -- If true, the vpa will be installed as a sub-chart
      enabled: true
      updater:
        enabled: false
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.16.1
      pullPolicy: Always

    controller:
      enabled: true
      flags:
        on-by-default: true
      resources:
        limits: {}
        requests:
          cpu: 25m
          memory: 256Mi
      # controller.podSecurityContext -- Defines the podSecurityContext for the controller pod
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
      # controller.securityContext -- The container securityContext for the controller container
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10324
        capabilities:
          drop:
            - ALL

    dashboard:
      enabled: true
      replicaCount: 2
      service:
        type: ClusterIP
        port: 80

      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: gdl.ksefuke-labs.com
            paths:
              - path: /
                type: ImplementationSpecific

        tls: 
          - secretName: prod-ksefuke-labs-tls
            hosts:
              - gdl.ksefuke-labs.com

      resources:
        limits: {}
        requests:
          cpu: 25m
          memory: 256Mi

      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault

      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10324
        capabilities:
          drop:
            - ALL

