apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kasm-workspaces
  namespace: kasm-workspaces
spec:
  interval: 30m
  chartRef:
    name: kasm-web
    kind: OCIRepository
  values:
    deploymentSize: "small"
    publicAddr: "kasm.ksefuke-labs.com"
    proxyService:
      type: ClusterIP

    ingress:
      enabled: true
      tls: true
      backendProtocol: http
      ingressClassName: "traefik"

    certificate:
      secretName: "prod-ksefuke-labs-tls"
      certManager:
        enabled: true
        addWildCard: true
        issuerName: "letsencrypt-production"
        issuerKind: "ClusterIssuer"

    kasmSecrets:
      create: false
      # kasmSecrets.name -- The name of the Kasm Password secret to create. If a value is provided here and `create=true`,
      # Helm will use that as the secret name. If `create=false` then you MUST provide the name of an existing Kasm Password
      # secret in your deployment namespace.
      name: "kasm-secrets"

    database:
      # database.standalone -- Setting standalone to true will prevent the deployment of the Kasm DB StatefulSet and requires
      # the user to have a self-hosted PostgreSQL Database v16 server already setup and awaiting connections. Use the below
      # database configuration values to connect to your external DB.
      # see, https://docs.kasm.com/docs/latest/how-to/remote_database#requirements for list of full db requirements.
      standalone: false
      # database.hostname -- The hostname of the external PostgreSQL server.
      # Only used when database.standalone is true.
      hostname: ""
      # database.port -- The port Kasm will use to connect to the PostgreSQL DB server
      port: 5432
      # database.kasmDbName -- The name of the database where Kasm is to be initialized and that Kasm services are to connect
      kasmDbName: kasm
      # database.kasmDbUser -- The name of the Kasm database User with READ/WRITE permission to the Kasm database
      kasmDbUser: kasmapp
      # database.kasmDbSecret -- The name of the Kasm database password secret to use for a user-created, custom Database password
      # secret value.
      # NOTE: Leave this empty to use the password created by this Helm chart. If you create a custom DB secret, define the `kasmDbSecret`
      # object below in the example format.
      kasmDbSecret: {}
      # Example Custom DB Secret configuration
      #   name: kasm-db-secret
      #   key: kasm-db-secret-key

      # database.postgresMasterUser -- An object defining the PostgreSQL DB Master user and the Kubernetes secret and key values for
      # the Master DB password. These credentials are only used by the `db-init-job` to create the `kasmDbName` database, the `kasmDbUser`
      # user account, set permissions for the user account, and initialize and pre-seed the Kasm Database.
      #
      postgresMasterUser: {}
      # Example DB Master User configuration
      #   username: postgres
      #   secret:
      #     name: postgres-secret
      #     key: db-password

    dbManagement:
      initialize: true
      upgrade:
        enable: false