apiVersion: v1
kind: Secret
metadata:
  name: kasm-secrets
  namespace: kasm-workspaces
type: Opaque
data:
  admin-password: "<base64-encoded value>"
  user-password: "<base64-encoded value>"
  db-password: "<base64-encoded value>"
  manager-token: "<base64-encoded value>"
  service-token: "<base64-encoded value>"