apiVersion: v1
kind: Secret
metadata:
    name: kasm-secrets
    namespace: kasm-workspaces
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:8aZ7e/ECV6Kd7DwCG95weK2uggZfbBwR,iv:I9LUw96ZKiiMoZ/gKW4qAXfFkcpvk/CancWpyddzgjw=,tag:vfUuwvbLWHm1VqHURrWwZg==,type:str]
    user-password: ENC[AES256_GCM,data:zPs9MJALKdZL1SkF1c9CSN/mONT0VfAo,iv:wA0uVSvM7Y0QZhaVAjkKzsfxMW8UoMQQLKAsm7/TAVQ=,tag:uL8MzU1c5VWG37Xd+kw4Pw==,type:str]
    db-password: ENC[AES256_GCM,data:15u64RagRCAioHvQTplYPToTk3YmWRW9,iv:x5AsURneszPPfAf4cGUrL/OyrpbtRGx0j2C61T3QGiM=,tag:DDnDmlTzh8T7hrmVIBf7xg==,type:str]
    manager-token: ENC[AES256_GCM,data:FMN/PvT8hr4aRZLnQERLIFfzb3hqiTh6,iv:Jue5AW9Z70VWRt6rtwHvA1I8LKlebFowmJPKy5p4MhE=,tag:Hx/VpyHnmB0hLTLRUKuLuA==,type:str]
    service-token: ENC[AES256_GCM,data:KnqEEcLPk8cq3hsGyQLLGRJFj+rxS+Z9,iv:kQak3nNTV/9BCIYtXWdQCSk97K1caNt18yiadResbaM=,tag:EtaSSROOVumdkg1mqIz8Kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL3ExVHhiT3BwZGU1RU1s
            T0pSUE16ZUh4MEw2eEhPVUVHeGZuWFR3MGxVCjcyRmpSZ3RxTlltcUtMY1RYL0ZM
            Y2ZLNUUrdUFUaTdnaFZHWWNnVWdsOXcKLS0tIG4vOEZKaEdRME9BZlVxU3owcXpr
            U1VBYmU3RU4ySlkvaUZGSzZoMHEybmcKWLDvdB2kaK9ZG34BbPOxQ/4DgHSrmeYj
            xHOL0yCRz0VuzyyEJS+vT1Xk29I+DKkzqM3i3J8XzoNfhJRptM9DUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T21:46:02Z"
    mac: ENC[AES256_GCM,data:PpmI4VTtgdjyg6USUpG81k6wgwnVGpx7Jbl8V73kq0PZcZ+46W8EAeDXnNCK+B+BwzwHj8nrB9HlMgeFzfIxolEZWkS3awFnZP+f9ykNBOLaWBjMIYiRvaAKpQif/jvZIPLlWJgvWAUWQ4ZpF9zVGAYo8VdvDx7zqtut6XxE28k=,iv:uGD5rlOXsgwhd9zp22m+MOZMqnQ/a6c8DOfTGtLZHow=,tag:46X8w2JCnT7HIWwSNrWBcw==,type:str]
    version: 3.13.3
