apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: calibre
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: lscr.io/linuxserver/calibre-web:latest
        name: calibre
        ports: 
          - containerPort: 8083
        envFrom:
          - configMapRef:
              name: calibre-configmap
        resources:
            limits:
              memory: 1Gi
        volumeMounts:
          - mountPath: /books
            name: calibre-books
          - mountPath: /config
            name: calibre-config
      initContainers:
        - name: fix-perms
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /books /config"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /books
              name: calibre-books
            - mountPath: /config
              name: calibre-config

      volumes:
        - name: calibre-web-books
          persistentVolumeClaim: # PVC Claim in storage.yaml
            claimName: calibre-book-pvc
        - name: calibre-web-config
          persistentVolumeClaim: # PVC Claim in storage.yaml
            claimName: calibre-config-pvc