apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-book-pvc
  namespace: calibre-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config-pvc
  namespace: calibre-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
